# action.yaml
name: 'Tonic Validate for PRs'
description: 'A GitHub Action that uses Tonic Validate to evaluate your LLM application output'
inputs:
  llm_response_path:
    description: 'Enter path to LLM response file'
    required: true
    type: string
  tonic_validate_project_id:
    description: 'Enter Tonic Validate server project ID'
    required: true
    type: string
  tonic_validate_api_key:
    description: 'Enter Tonic Validate server API key'
    required: true
    type: string
  commit_id:
    description: 'Commit ID for the current action run'
    required: false
  repo_url:
    description: 'URL of the repository'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash        
    - name: Evaluate
      id: tonic-validate
      env:
        TONIC_VALIDATE_GITHUB_ACTION: true
        TONIC_VALIDATE_SERVER_PROJECT_ID: ${{ inputs.tonic_validate_project_id }}
        TONIC_VALIDATE_SERVER_API_KEY: ${{ inputs.tonic_validate_api_key }}
        VALIDATE_RESPONSES_PATH: ${{ github.workspace	 }}/${{ inputs.llm_response_path }}
        GITHUB_COMMIT_ID: ${{ inputs.commit_id }}
        GITHUB_REPO_URL: ${{ inputs.repo_url }}
      run: python ${{ github.action_path }}/src/runner.py
      shell: bash
branding:
  color: gray-dark
  icon: server        