name: Merge Action

on: [push]

jobs:
  tonic_validate:
    runs-on: ubuntu-latest
    name: Tonic Validate
    env:
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY}}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT}}
      TONIC_VALIDATE_API_KEY: ${{ secrets.TONIC_VALIDATE_API_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4    
      - name: Run Tonic Validate Action
        uses: ./
        with:
          llm_response_path: ./sample.json
          tonic_validate_project_id: ${{ secrets.TONIC_VALIDATE_PROJECT_ID }}
  